update

diff --git a/.github/workflows/generate-env.yml b/.github/workflows/generate-env.yml
--- a/.github/workflows/generate-env.yml
+++ b/.github/workflows/generate-env.yml
@@ -3,14 +3,20 @@ on:
   push:
     branches:
       - main
+
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+
       - name: Create .env from GitHub Secrets
         run: |
           echo "VITE_SECRET_MESSAGE=${{ secrets.MY_SECRET }}" > .env
+
+      - name: Show .env content
+        run: cat .env || echo ".env not found"
+
       - name: Upload .env
         uses: actions/upload-artifact@v4
         with:
